USE [DOUCE_DB]
GO
INSERT [dbo].[Perfume] ([Id], [Name], [Brand], [Manufacturer], [ShortDescription], [Description], [Composition], [Ingredients], [StockQuantity], [TopPerfumed], [MiddlePerfumed], [BasePerfumed], [PriceInfo], [FragranceNotes], [Status], [ImageUrl], [CreatedAt], [UpdatedAt]) VALUES (N'f8b7f2d0-12bd-41e8-85aa-275960268b89', N'ANGELISM', N'PHALG', N'PHALG', N'Đầy đặc những nốt hương hoa trắng vàng, cổ điển và xạ hoa chính là sắc thái bao trùm sáng tạo hương này.', N'<p>Ngay từ khoảnh khắc đầu tiên, Hoa Nhài bừng sáng, trong trẻo và rực rỡ. Khi lan tỏa, Hoa Hồng phát nhẹ xuất hiện, mềm mịn như đôi cánh thiên thần, hòa cùng Mộc Lan đầy đặn, sáng bóng, định hình rõ nét mùi hương.</p>
<p>Cuối cùng, Xạ Hương Trắng ôm trọn tất cả, trong veo nhưng vững chãi, lan tỏa mà không phai nhạt, để lại một dấu ấn nhẹ nhàng nhưng không thể lãng quên.</p>
<p>Angelism là một mùi hương có hình khối, có trọng lượng, có sắc bám tỏa, như những thiên thần, ho lặng lẽ nhưng rực rỡ, thanh khiết nhưng không thể bị lãng quên.</p>', N'', N'[{"Name": "Mộc Lan", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Hoa Hồng", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Hoa Nhài", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Xạ Hương", "ImageUrl": "/images/ingredient.png", "Description": ""}]', 100, N'Hoa Mộc Lan, Dưa Gang, Quả Đào, Cam', N'Hoa Lan Nam Phi, Hoa Nhài, Hoa Hồng', N'Xạ Hương, Hương Vani, Gỗ Tuyết Tùng', N'[{"VolumeMl":50,"Price":720000,"Currency":"VND"},{"VolumeMl":15,"Price":320000,"Currency":"VND"}]', N'{"Citrus":false,"Floral":true,"Fruity":true,"Woody":false,"Musky":true,"Oriental":false,"Spicy":false,"Tobacco":false,"Gourmand":false}', N'Available', N'/images/angelism.jpg', CAST(N'2025-04-12T12:51:21.5266667' AS DateTime2), CAST(N'2025-04-12T12:51:21.5266667' AS DateTime2))
GO
INSERT [dbo].[Perfume] ([Id], [Name], [Brand], [Manufacturer], [ShortDescription], [Description], [Composition], [Ingredients], [StockQuantity], [TopPerfumed], [MiddlePerfumed], [BasePerfumed], [PriceInfo], [FragranceNotes], [Status], [ImageUrl], [CreatedAt], [UpdatedAt]) VALUES (N'71362967-3b39-4ab1-80f5-3f8454a8badc', N'HANDS OF MIDAS', N'PHALG', N'PHALG', N'Hương thơm phong phú, quyền lực với cà phê, quế, vani và gỗ tuyết tùng.', N'<p>Hương thơm phong phú của Hands of Midas là lời mời gọi đầy quyền lực, khơi mở những đỉnh cao mới trong mọi giác quan.</p>
    <p>Mở đầu với Hands of Midas, bạn sẽ bị cuốn ngay vào sự hòa quyện sắc sảo giữa Cam Đắng, Tiêu Hồng và Nhục Đậu Khấu – một sự khởi đầu đầy táo bạo nhưng không kém phần tinh tế.</p>
    <p>Lớp hương giữa tiếp tục dẫn dắt với sự hòa quyện của Cà Phê và Quế Lát – hai nốt hương chủ đạo, kết hợp cùng Hoa Hồng và Đinh Hương để tạo nên một chiều sâu quyến rũ, ấm áp nhưng không kém phần bí ẩn.</p>
    <p>Cuối cùng, Vani và Đậu Tonka hòa quyện cùng Gỗ Tuyết Tùng và Hổ Phách, mang đến một hậu hương kéo dài đầy ngọt ngào, quyền lực và sâu lắng, khiến bạn không thể nào quên được Hands of Midas.</p>', N'', N'[{"Name": "Cà Phê", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Vani", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Quế Lát", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Gỗ Tuyết Tùng", "ImageUrl": "/images/ingredient.png", "Description": ""}]', 100, N'Cam Đắng, Tiêu Hồng, Nhục Đậu Khấu', N'Cà Phê, Quế Lát, Hoa Hồng, Đinh Hương', N'Vani, Đậu Tonka, Gỗ Tuyết Tùng, Hổ Phách', N'[{"VolumeMl":50,"Price":925000,"Currency":"VND"},{"VolumeMl":15,"Price":415000,"Currency":"VND"}]', N'{"Citrus":true,"Floral":false,"Fruity":false,"Woody":true,"Musky":false,"Oriental":true,"Spicy":true,"Gourmand":true}', N'Available', N'/images/hands_of_midas.jpg', CAST(N'2025-04-12T12:56:01.2866667' AS DateTime2), CAST(N'2025-04-12T12:56:01.2866667' AS DateTime2))
GO
INSERT [dbo].[Perfume] ([Id], [Name], [Brand], [Manufacturer], [ShortDescription], [Description], [Composition], [Ingredients], [StockQuantity], [TopPerfumed], [MiddlePerfumed], [BasePerfumed], [PriceInfo], [FragranceNotes], [Status], [ImageUrl], [CreatedAt], [UpdatedAt]) VALUES (N'1cf95b4c-2f55-422e-8122-b42b7d064357', N'GILDED TOBAC', N'PHALG', N'PHALG', N'Tổ hợp hương thuốc lá, gỗ, khói bùng đầy đầy ấn tượng.', N'<p>Gilded Tobac là một mùi hương thuốc lá hiếm và ấn tượng. Dựa trên tổ hợp kinh điển Thuốc lá – Vani, nhưng thay vì lặp lại lối mòn, Gilded Tobac khai thác sắc thái Smokey Sweet Tobacco – thuốc lá khô nhưng ngọt, đượm khói đầy nhưng bùng tỏa tự nhiên.</p>
<p>Ngay từ những nốt hương đầu, Saffron vàng gắt hòa cùng chất hoang dại của da thuộc, đem xuyên cay gỗ thơm ấm, để tôn nên độ tương phản đầy cuốn hút. Tầng hương cuối lắng dịu lên, Vani Madagascar mềm mại sắc sảo, ẩn hiện như mật lăn sương, tưởng chừng mong manh nhưng không ngừng ngân vang vững vàng.</p>
<p>Gilded Tobac không chỉ là một mùi hương – mà là một tuyển ngắn kinh chất: bản tình, trầm ấm nhưng không khuôn khổ.</p>', N'', N'[{"Name": "Thuốc Lá Ngọt", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Gỗ Đàn Hương", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Rượu Rum Ngọt", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Vani Madagascar", "ImageUrl": "/images/ingredient.png", "Description": ""}]', 100, N'Cam Bergamot, Rượu Rum Ngọt, Hoa Nhật Tây', N'Thuốc Lá Ngọt, Vani Madagascar, Hoa Hồng, Gỗ Tuyết Tùng', N'Đậu Tonka, Mật Ong, Gỗ Đàn Hương, Xạ Hương', N'[{"VolumeMl":50,"Price":730000,"Currency":"VND"},{"VolumeMl":15,"Price":330000,"Currency":"VND"}]', N'{"Citrus":false,"Floral":false,"Fruity":false,"Woody":true,"Musky":true,"Oriental":true,"Spicy":false,"Tobacco":true,"Gourmand":true}', N'Available', N'/images/gilded_tobac.jpg', CAST(N'2025-04-12T12:52:48.6700000' AS DateTime2), CAST(N'2025-04-12T12:52:48.6700000' AS DateTime2))
GO
INSERT [dbo].[Perfume] ([Id], [Name], [Brand], [Manufacturer], [ShortDescription], [Description], [Composition], [Ingredients], [StockQuantity], [TopPerfumed], [MiddlePerfumed], [BasePerfumed], [PriceInfo], [FragranceNotes], [Status], [ImageUrl], [CreatedAt], [UpdatedAt]) VALUES (N'76cd2b98-48c7-45ad-8cf5-bd0e445c1b8a', N'FORBIDDEN SWEET', N'PHALG', N'PHALG', N'Thiết lập hương gourmand tối: ngọt đầy, khói nhẹ và sánh đặc.', N'<p>Forbidden Sweet là mùi hương gourmand ngọt ngào, nhưng là cái ngọt tối, đầy, lắng lại như dư vị của một bí mật chưa từng hé mở.</p>
<p>Mở đầu bằng phảng phất một quả lê mọng nước, vào căn nhẹ da tỏa vị ngọt thanh, quyện cùng vani sánh đặc, phủ lấy hương cà phê đen. Một chút khói nhẹ, một chút mảng choy, tất cả làm nên cơ thể hương sâu lắng đọng cần trải đầy.</p>
<p>Cà phê trong Forbidden Sweet không phải tích espresso sắc bén, mà là cà phê ngấm vào da thịt, ấm áp, dịu êm, kéo mọi giác quan vào một vùng tối đầy quyến rũ. Ngọt, nhưng không hề nhẹ.</p>
<p>Forbidden Sweet là một cám dỗ không lời – thứ khiến người ta sa vào, mà không hề hối tiếc.</p>', N'', N'[{"Name": "Cà Phê", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Vani", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Quả Lê", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Gỗ Tuyết Tùng", "ImageUrl": "/images/ingredient.png", "Description": ""}]', 100, N'Quả Lê, Tiểu Hồng, Hoa Cam', N'Cà Phê, Hoa Nhài, Nghệ Nhãn, Cam Thảo', N'Vanilla, Hoắc Hương, Gỗ Tuyết Tùng, Cashmerean', N'[{"VolumeMl":50,"Price":920000,"Currency":"VND"},{"VolumeMl":15,"Price":410000,"Currency":"VND"}]', N'{"Citrus":false,"Floral":false,"Fruity":true,"Woody":false,"Musky":true,"Oriental":true,"Spicy":false,"Tobacco":false,"Gourmand":true}', N'Available', N'/images/forbidden_sweet.jpg', CAST(N'2025-04-12T12:52:09.9533333' AS DateTime2), CAST(N'2025-04-12T12:52:09.9533333' AS DateTime2))
GO
INSERT [dbo].[Perfume] ([Id], [Name], [Brand], [Manufacturer], [ShortDescription], [Description], [Composition], [Ingredients], [StockQuantity], [TopPerfumed], [MiddlePerfumed], [BasePerfumed], [PriceInfo], [FragranceNotes], [Status], [ImageUrl], [CreatedAt], [UpdatedAt]) VALUES (N'c3624c00-4155-477d-a175-d905acedd7da', N'FRÉQUENCE', N'PHALG', N'PHALG', N'Mang đến tầng hương đầy mê hoặc giữa hương gỗ cay nồng trầm ấm và chất xanh mát của khu rừng nguyên sinh hùng vĩ sau cơn mưa rào.', N'<p>Fréquence tựa như một dòng chảy hương cay nồng và mê hoặc, một tần số rung động len lỏi vào mọi giác quan.</p>
<p>Hoắc hương sâu thẳm, ấm mượt, quấn lấy từng thớ gỗ khô, dẫn lối cho quế và nhục đậu khấu bùng lên. Chúng hòa vào nhau, tạo nên một tiết tấu êm trầm, đầy nội lực, như một giai điệu không ngừng dội lại trong tâm trí.</p>
<p>Fréquence là mùi hương có độ bền chuyên mẫn vượt lối nhất, sau cái trầm ấm đọng rắn, mở ra mẽ thanh thoát của Citrus dẫn nhịp ra và thấm đẫm, như một sự cộng hưởng trọn vẹn – nơi sắc thái không ẩm ướt phố trường, mà ở đó rừng đồng lan tỏa, kéo dài, và không thể nào quên.</p>', N'', N'[{"Name": "Hoắc Hương", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Quế", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Nhục Đậu Khấu", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Cam Chanh", "ImageUrl": "/images/ingredient.png", "Description": ""}]', 100, N'Bạch Đậu Khấu, Cam Chanh, Bưởi', N'Quế, Gỗ Hương, Nhục Đậu Khấu', N'Hổ Phách, Hoắc Hương, Gỗ Hương Bài', N'[{"VolumeMl":50,"Price":860000,"Currency":"VND"},{"VolumeMl":15,"Price":380000,"Currency":"VND"}]', N'{"Citrus":true,"Floral":false,"Fruity":false,"Woody":true,"Musky":false,"Oriental":true,"Spicy":true,"Tobacco":false,"Gourmand":false}', N'Available', N'/images/frequence.jpg', CAST(N'2025-04-12T12:45:38.8966667' AS DateTime2), CAST(N'2025-04-12T12:45:38.8966667' AS DateTime2))
GO
INSERT [dbo].[Perfume] ([Id], [Name], [Brand], [Manufacturer], [ShortDescription], [Description], [Composition], [Ingredients], [StockQuantity], [TopPerfumed], [MiddlePerfumed], [BasePerfumed], [PriceInfo], [FragranceNotes], [Status], [ImageUrl], [CreatedAt], [UpdatedAt]) VALUES (N'e971e0c4-ac80-48e5-9da0-f480fcd0297c', N'APHRODITE', N'PHALG', N'PHALG', N'Vườn Thần Thoại đầy quả mọng và hoa tươi bừng lên trong trẻo, thánh khiết mà rực rỡ.', N'<p>Khoác trên thân mùi hương Aphrodite chính là sở hữu một vẻ đẹp khiến người ta say lòng.</p>
<p>Tựa như bước vào một khu vườn rực rỡ trong buổi sớm tinh mơ, Aphrodite mở đầu bằng hương Vải Taisō căng mọng và trong trẻo. Hoa Hồng Thổ Nhĩ Kỳ bừng nở kiêu kỳ và rực rỡ. Linh Lan Thung Lũng khẽ len lỏi, mang theo hơi thở xanh mát, khiến cả không gian bừng lên sức sống. Từng giọt từng giọt Xạ Hương Trắng sạch sẽ và thanh thuần lấp lánh trên da khơi lên niềm riêng chiếm hữu, kéo mọi ánh mắt không thể xa rời.</p>
<p>Aphrodite là mùi hương sinh ra để quyến rũ – và không cần xin phép để làm điều đó.</p>', N'', N'[{"Name": "Quả Vải", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Hoa Hồng Thổ Nhĩ Kỳ", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Xạ Hương Trắng", "ImageUrl": "/images/ingredient.png", "Description": ""}, {"Name": "Cashmeran", "ImageUrl": "/images/ingredient.png", "Description": ""}]', 100, N'Cam Bergamot, Cây Đại Hoàng, Quả Vải', N'Hoa Hồng Thổ Nhĩ Kỳ, Hoa Mẫu Đơn, Hoa Linh Lan Thung Lũng', N'Hương Vani, Xạ Hương trắng, Hương Cashmeran', N'[{"VolumeMl":50,"Price":760000,"Currency":"VND"},{"VolumeMl":15,"Price":360000,"Currency":"VND"}]', N'{"Citrus":true,"Floral":true,"Fruity":true,"Woody":false,"Musky":false,"Oriental":false,"Spicy":false,"Tobacco":false,"Gourmand":false}', N'Available', N'/images/aphrodite.jpg', CAST(N'2025-04-12T12:43:18.4600000' AS DateTime2), CAST(N'2025-04-12T12:43:18.4600000' AS DateTime2))
GO
